<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="11" total="11" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="612" started-at="2016-04-11T10:52:26Z" finished-at="2016-04-11T10:52:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="612" started-at="2016-04-11T10:52:26Z" finished-at="2016-04-11T10:52:26Z">
      <class name="UnitTests.UserDaoTests">
        <test-method status="FAIL" signature="testAddUser(POJO.User)[pri:0, instance:UnitTests.UserDaoTests@4520ebad]" name="testAddUser" duration-ms="484" started-at="2016-04-11T13:52:26Z" data-provider="user" finished-at="2016-04-11T13:52:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[POJO.User@59ec2012]]>
              </value>
            </param>
          </params>
          <exception class="DAO.UserDAOException">
            <message>
              <![CDATA[The username exist, please choose different name]]>
            </message>
            <full-stacktrace>
              <![CDATA[DAO.UserDAOException: The username exist, please choose different name
	at DAO.UserDAO.addUser(UserDAO.java:57)
	at UnitTests.UserDaoTests.testAddUser(UserDaoTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- DAO.UserDAOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddUser -->
        <test-method status="FAIL" signature="testAddUser(POJO.User)[pri:0, instance:UnitTests.UserDaoTests@4520ebad]" name="testAddUser" duration-ms="3" started-at="2016-04-11T13:52:26Z" data-provider="user" finished-at="2016-04-11T13:52:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[POJO.User@fad74ee]]>
              </value>
            </param>
          </params>
          <exception class="DAO.UserDAOException">
            <message>
              <![CDATA[The username exist, please choose different name]]>
            </message>
            <full-stacktrace>
              <![CDATA[DAO.UserDAOException: The username exist, please choose different name
	at DAO.UserDAO.addUser(UserDAO.java:57)
	at UnitTests.UserDaoTests.testAddUser(UserDaoTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- DAO.UserDAOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddUser -->
        <test-method status="FAIL" signature="testAddUser(POJO.User)[pri:0, instance:UnitTests.UserDaoTests@4520ebad]" name="testAddUser" duration-ms="3" started-at="2016-04-11T13:52:26Z" data-provider="user" finished-at="2016-04-11T13:52:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[POJO.User@32d2fa64]]>
              </value>
            </param>
          </params>
          <exception class="DAO.UserDAOException">
            <message>
              <![CDATA[The username exist, please choose different name]]>
            </message>
            <full-stacktrace>
              <![CDATA[DAO.UserDAOException: The username exist, please choose different name
	at DAO.UserDAO.addUser(UserDAO.java:57)
	at UnitTests.UserDaoTests.testAddUser(UserDaoTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- DAO.UserDAOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddUser -->
        <test-method status="FAIL" signature="testAddUser(POJO.User)[pri:0, instance:UnitTests.UserDaoTests@4520ebad]" name="testAddUser" duration-ms="4" started-at="2016-04-11T13:52:26Z" data-provider="user" finished-at="2016-04-11T13:52:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[POJO.User@587d1d39]]>
              </value>
            </param>
          </params>
          <exception class="DAO.UserDAOException">
            <message>
              <![CDATA[The username exist, please choose different name]]>
            </message>
            <full-stacktrace>
              <![CDATA[DAO.UserDAOException: The username exist, please choose different name
	at DAO.UserDAO.addUser(UserDAO.java:57)
	at UnitTests.UserDaoTests.testAddUser(UserDaoTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- DAO.UserDAOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddUser -->
        <test-method status="FAIL" signature="testAddUser(POJO.User)[pri:0, instance:UnitTests.UserDaoTests@4520ebad]" name="testAddUser" duration-ms="5" started-at="2016-04-11T13:52:26Z" data-provider="user" finished-at="2016-04-11T13:52:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[POJO.User@38bc8ab5]]>
              </value>
            </param>
          </params>
          <exception class="DAO.UserDAOException">
            <message>
              <![CDATA[The username exist, please choose different name]]>
            </message>
            <full-stacktrace>
              <![CDATA[DAO.UserDAOException: The username exist, please choose different name
	at DAO.UserDAO.addUser(UserDAO.java:57)
	at UnitTests.UserDaoTests.testAddUser(UserDaoTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- DAO.UserDAOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddUser -->
        <test-method status="FAIL" signature="testAddUser(POJO.User)[pri:0, instance:UnitTests.UserDaoTests@4520ebad]" name="testAddUser" duration-ms="3" started-at="2016-04-11T13:52:26Z" data-provider="user" finished-at="2016-04-11T13:52:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[POJO.User@4abdb505]]>
              </value>
            </param>
          </params>
          <exception class="DAO.UserDAOException">
            <message>
              <![CDATA[The username exist, please choose different name]]>
            </message>
            <full-stacktrace>
              <![CDATA[DAO.UserDAOException: The username exist, please choose different name
	at DAO.UserDAO.addUser(UserDAO.java:57)
	at UnitTests.UserDaoTests.testAddUser(UserDaoTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- DAO.UserDAOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddUser -->
        <test-method status="FAIL" signature="testAddUser(POJO.User)[pri:0, instance:UnitTests.UserDaoTests@4520ebad]" name="testAddUser" duration-ms="3" started-at="2016-04-11T13:52:26Z" data-provider="user" finished-at="2016-04-11T13:52:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[POJO.User@60285225]]>
              </value>
            </param>
          </params>
          <exception class="DAO.UserDAOException">
            <message>
              <![CDATA[The username exist, please choose different name]]>
            </message>
            <full-stacktrace>
              <![CDATA[DAO.UserDAOException: The username exist, please choose different name
	at DAO.UserDAO.addUser(UserDAO.java:57)
	at UnitTests.UserDaoTests.testAddUser(UserDaoTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- DAO.UserDAOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddUser -->
        <test-method status="FAIL" signature="testAddUser(POJO.User)[pri:0, instance:UnitTests.UserDaoTests@4520ebad]" name="testAddUser" duration-ms="3" started-at="2016-04-11T13:52:26Z" data-provider="user" finished-at="2016-04-11T13:52:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[POJO.User@cb51256]]>
              </value>
            </param>
          </params>
          <exception class="DAO.UserDAOException">
            <message>
              <![CDATA[The username exist, please choose different name]]>
            </message>
            <full-stacktrace>
              <![CDATA[DAO.UserDAOException: The username exist, please choose different name
	at DAO.UserDAO.addUser(UserDAO.java:57)
	at UnitTests.UserDaoTests.testAddUser(UserDaoTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- DAO.UserDAOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddUser -->
        <test-method status="FAIL" signature="testAddUser(POJO.User)[pri:0, instance:UnitTests.UserDaoTests@4520ebad]" name="testAddUser" duration-ms="3" started-at="2016-04-11T13:52:26Z" data-provider="user" finished-at="2016-04-11T13:52:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[POJO.User@5bcea91b]]>
              </value>
            </param>
          </params>
          <exception class="DAO.UserDAOException">
            <message>
              <![CDATA[The username exist, please choose different name]]>
            </message>
            <full-stacktrace>
              <![CDATA[DAO.UserDAOException: The username exist, please choose different name
	at DAO.UserDAO.addUser(UserDAO.java:57)
	at UnitTests.UserDaoTests.testAddUser(UserDaoTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- DAO.UserDAOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddUser -->
        <test-method status="FAIL" signature="testAddUser(POJO.User)[pri:0, instance:UnitTests.UserDaoTests@4520ebad]" name="testAddUser" duration-ms="3" started-at="2016-04-11T13:52:26Z" data-provider="user" finished-at="2016-04-11T13:52:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[POJO.User@44c8afef]]>
              </value>
            </param>
          </params>
          <exception class="DAO.UserDAOException">
            <message>
              <![CDATA[The username exist, please choose different name]]>
            </message>
            <full-stacktrace>
              <![CDATA[DAO.UserDAOException: The username exist, please choose different name
	at DAO.UserDAO.addUser(UserDAO.java:57)
	at UnitTests.UserDaoTests.testAddUser(UserDaoTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- DAO.UserDAOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddUser -->
        <test-method status="FAIL" signature="testAddUser(POJO.User)[pri:0, instance:UnitTests.UserDaoTests@4520ebad]" name="testAddUser" duration-ms="9" started-at="2016-04-11T13:52:26Z" data-provider="user" finished-at="2016-04-11T13:52:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[POJO.User@262b2c86]]>
              </value>
            </param>
          </params>
          <exception class="DAO.UserDAOException">
            <message>
              <![CDATA[The username exist, please choose different name]]>
            </message>
            <full-stacktrace>
              <![CDATA[DAO.UserDAOException: The username exist, please choose different name
	at DAO.UserDAO.addUser(UserDAO.java:57)
	at UnitTests.UserDaoTests.testAddUser(UserDaoTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- DAO.UserDAOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddUser -->
      </class> <!-- UnitTests.UserDaoTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
